services:
  backend:
    build:
      context: ./todo-app/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - logstash
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo
    volumes:
      - .:/app
    command: ["yarn", "start"]

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.3
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  mongo_data: